const colors = {
  light: {
    text: '#00FFFF',
    tint: '#00FFFF',
    background: '#0A0A12',
    foreground: '#00FFFF',
    card: '#0F0F1A',
    cardForeground: '#00FFFF',
    primary: '#00FFFF',
    primaryForeground: '#0A0A12',
    secondary: '#FF00FF',
    secondaryForeground: '#0A0A12',
    muted: '#0F0F1A',
    mutedForeground: '#444466',
    accent: '#FF00FF',
    accentForeground: '#0A0A12',
    destructive: '#FF0044',
    destructiveForeground: '#FFFFFF',
    border: '#1A1A2A',
    input: '#1A1A2A',
  },
  dark: {
    text: '#00FFFF',
    tint: '#00FFFF',
    background: '#0A0A12',
    foreground: '#00FFFF',
    card: '#0F0F1A',
    cardForeground: '#00FFFF',
    primary: '#00FFFF',
    primaryForeground: '#0A0A12',
    secondary: '#FF00FF',
    secondaryForeground: '#0A0A12',
    muted: '#0F0F1A',
    mutedForeground: '#444466',
    accent: '#FF00FF',
    accentForeground: '#0A0A12',
    destructive: '#FF0044',
    destructiveForeground: '#FFFFFF',
    border: '#1A1A2A',
    input: '#1A1A2A',
  },
  radius: 8,
};

export default colors;
